### ISSUE TITLE
[question] Matching key exists from one RDF in second RDF file, can I use nxparser?

### ISSUE THREAD

**Issue by archenroot** [nxparser/nxparser#21]
Hi guys,

this is pure question only. I use Jena TBD to load 2 files, after which I do basic validation if some keys from one file are found all in second file, that's it.

Can I do this via nxxparser? and maybe even faster?

Thanks,

Ladislav

**Comment by kaefer3000** [comment]
Whatever you consider a key... you can indeed easily scan through one file and collect "keys" in, say, a HashSet, and, scanning the second file, check whether the "keys" are contained. Cheers!

**Comment by archenroot** [comment]
Ok, so for this purpose can i use nxpareser to load RDF into hashset can be used then? Sorry, so far I was just in Jena option, but this look maybe more easy to use, so I don't need full backend tripplestore engine. Thank you.
